apiVersion: apps/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app : sample-app
  name: sample-app
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Deployment
    name: sample-app
  targetCPUUtilizationPercentage: 80
