apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: frodo
commonLabels:
  app: sample-app
images:
- name: argoproj/rollouts-demo
  newTag: blue
resources:
- ../../base

nameSuffix: -develop
